---
title: "Homework 5 Solution"
author: "Brian Lois"
date: "3/5/2017"
output: pdf_document
---

```{r setup, include=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(AppliedPredictiveModeling)
library(class)
library(kernlab)
data(hepatic)
set.seed(111)
```

## 1.

### a.

Stratified sampling should be used because of the small number of 'Severe' samples.
```{r}
train_indices <- createDataPartition(injury, p = .8, list = FALSE)
combined_data <- cbind(bio, injury)
train_data <- combined_data[train_indices, ]
test_data <- combined_data[-train_indices, ]
```

### b & c.
```{r, warning=FALSE}
train_data$none <- train_data$injury == 'None'
train_data$mild <- train_data$injury == 'Mild'
train_data$severe <- train_data$injury == 'Severe'

make_formula <- function(target){
  input_features <- colnames(train_data)[1:184]
  input_features_string<- paste(input_features, collapse = ' + ')
  formula_string <- paste(target, ' ~ ', input_features_string)
  formula <- as.formula(formula_string)
  return(formula)
}

models <- list()
preds <- as.data.frame(test_data$injury)
for (outcome in c('none', 'mild', 'severe')){
  models[[outcome]] <- glm(make_formula(outcome), data = train_data, family = binomial())
  preds[[outcome]] <- predict(models[[outcome]], test_data)
}

preds$pc_num <- max.col(preds[ ,2:4])
preds$predicted_class[preds$pc_num == 1] <- 'None'
preds$predicted_class[preds$pc_num == 2] <- 'Mild'
preds$predicted_class[preds$pc_num == 3] <- 'Severe'

head(preds)
```

### d.

Print the confusion matrix
```{r}
(conf_mat <- table(preds$`test_data$injury`, preds$predicted_class))
```

Accuracy:
```{r}
(conf_mat[1,1] + conf_mat[2,2] + conf_mat[3,3]) / nrow(test_data)
```

Since 51% of the data are 'Mild' we could do better by predicting 'Mild' for everything.

## 2.
```{r}
accuracy <- c()
for (k in seq(1, 100, 1)){
  model <- knn(train_data[,1:184], test_data[,1:184], train_data$injury, k = k)
  conf_mat <- table(model, test_data$injury)
  acc <- (conf_mat[1,1] + conf_mat[2,2] + conf_mat[3,3]) / nrow(test_data)
  accuracy <- c(accuracy, acc) 
}
plot(accuracy, type = 'l')
```

From this plot, I would choose k = 40.

## 3.
```{r, warning=FALSE, message=FALSE}
train_data <- train_data[train_data$injury != 'Severe', ]
test_data <- test_data[test_data$injury != 'Severe', ]

train_data$injury <- factor(train_data$injury)
test_data$injury <- factor(test_data$injury)

for (ker in c('vanilladot', 'rbfdot')){
  for (C in seq(.1, 5.1, 1)){
    svm_model <- ksvm(x = as.matrix(train_data[ ,1:184]), 
                      y = train_data$injury, 
                      kernel = ker,
                      C = C)
    preds <- predict(svm_model, as.matrix(test_data[,1:184]))
    conf_mat <- table(preds, test_data$injury)
    acc <- (conf_mat[1,1] + conf_mat[2,2]) / nrow(test_data)
    print(c(ker, C, acc))
  }
}

```




